# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
