# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_box_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.IntegerField(choices=[(10, 'Open'), (20, 'Expired'), (30, 'Sent'), (50, 'On Queue'), (40, 'Closed')], default=10),
        ),
    ]
