# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_auto_20170519_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
