version: '2'

services:
  web:
    extends:
      file: common.yml
      service: app
    ports:
      - "80:8000"

  celery:
    extends:
      file: common.yml
      service: app
    command: pipenv run celery -A hawkpost worker --beat -l info
    volumes:
      - "./gpg_home:/home/user/.gnupg"

  mail_debug:
    extends:
      file: common.yml
      service: app
    command: pipenv run python manage.py mail_debug --settings hawkpost.settings.development --use-settings
    ports:
      - "1025:1025"
    environment:
      EMAIL_HOST: 0.0.0.0
      EMAIL_PORT: 1025

  db:
    image: postgres:9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hawkpost
      - POSTGRES_PASSWORD=hawkpost
      - POSTGRES_DB=hawkpost_dev

  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
