version: "2"

services:
  web:
    extends:
      file: common.yml
      service: app
    ports:
      - "80:8000"

  celery:
    extends:
      file: common.yml
      service: app
    command: pipenv run celery -A hawkpost worker --beat -l info
    volumes:
      - "./gpg_home:/home/user/.gnupg"

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hawkpost
      - POSTGRES_PASSWORD=hawkpost
      - POSTGRES_DB=hawkpost_dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
