# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_auto_20160310_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
