# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
