# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 17:48
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_auto_20160330_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
