# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='server_signed',
            field=models.BooleanField(default=False),
        ),
    ]
