# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0009_auto_20170519_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-pt', 'Portuguese')], default='en-us', max_length=16, verbose_name='Language'),
        ),
    ]
